import type { MQTT } from './mqtt.js';
import type { BaseEntity } from './baseEntity.js';
export declare const COMMAND_MAPPING: Record<string, string>;
type DeviceQueryParams = Record<string, string>;
export declare class WaterHeater {
    mqtt: MQTT;
    pendingCommands: Record<string, string> | undefined;
    sensors: Record<string, BaseEntity>;
    deviceId: string;
    moduleAPI?: string;
    moduleFirmwareVersion?: string;
    masterFirmwareVersion?: string;
    masterModelId?: string;
    displayFirmwareVersion?: string;
    wifiFirmwareVersion?: string;
    updateRate?: string;
    mode?: string;
    setPoint?: number;
    units?: string;
    leakDetected?: string;
    maxSetPoint?: string;
    grid?: string;
    airFilterStatus?: string;
    condensePumpFail?: string;
    availableModes: string[];
    heating?: string;
    hotWaterVolume?: string;
    leak?: string;
    dryFire?: string;
    elementFail?: string;
    tankSensorFail?: string;
    ecoError?: string;
    masterDisplayFail?: string;
    compressorSensorFail?: string;
    systemSensorFail?: string;
    systemFail?: string;
    upperTemperature?: string;
    lowerTemperature?: string;
    faultCodes?: string;
    unConnectNumber?: string;
    addressData?: string;
    signalStrength?: string;
    constructor(mqtt: MQTT);
    bootstrap(queryParams: DeviceQueryParams): Promise<void>;
    createUpdateSensor(queryParams: DeviceQueryParams, key: string, type: new (...args: any[]) => BaseEntity, config?: Record<string, unknown>, ...args: unknown[]): Promise<void>;
    convertQueryParams(queryParams: DeviceQueryParams): Promise<void>;
    updatePendingCommands(key: string, value: string): void;
    toResponse(): Record<string, string>;
    generateDeviceConfig(): Record<string, unknown>;
    generateModeMappingTemplate(inverse: boolean): string;
    listenForCommands(): Promise<void>;
    createHomeAssistantConfig(): Promise<void>;
    updateMQTTData(): Promise<void>;
}
export {};
//# sourceMappingURL=waterheater.d.ts.map